name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Pre-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event"
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  deploy:
    name: Deploy
    needs: Pre-Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_extra_cidrs: ${{ secrets.TF_VAR_extra_cidrs }}
      TF_VAR_in_gihub_action: true
      BACKEND_BUCEKT_NAME: ${{ secrets.BACKEND_BUCEKT_NAME }}
      BACKEND_BUCKET_KEY: ${{ secrets.BACKEND_BUCKET_KEY }}
      BACKEND_BUCKET_REGION: ${{ secrets.BACKEND_BUCKET_REGION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: create backend.tf & variables.tf
      run: |
        cat <<EOF > backend.tf
        terraform {
          backend "s3" {
            bucket = "$BACKEND_BUCEKT_NAME"
            key    = "$BACKEND_BUCKET_KEY"
            region = "$BACKEND_BUCKET_REGION"
          }
        }
        EOF
        sed 's/<your_ssh_public_key>/null/' <variables.tf.examples >variables.tf

    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.12.5

    - name: Tofu Init
      id: init
      run: tofu init

    - name: Tofu Format
      id: fmt
      run: tofu fmt -check -recursive
      continue-on-error: true

    - name: Tofu Validate
      id: validate
      run: tofu validate

    - name: Tofu Plan
      id: plab
      run: tofu plan

    - name: Tofu Apply
      run: tofu apply -auto-approve